#include "stm32f4xx.h"

void PWM_init(void);
void PWM_CH4(void);

uint32_t tim1_ccr1;

int main(void){
	PWM_init();
	//PWM_CH4();
	
	while(1){
	}
	
	return 0;
}
 
void PWM_init(void){
	RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	
	GPIOA->MODER &= ~(GPIO_MODER_MODE8_0);
	GPIOA->MODER |= GPIO_MODER_MODE8_1;
	GPIOA->MODER &= ~(GPIO_MODER_MODE9_0);
	GPIOA->MODER |= GPIO_MODER_MODE9_1;
	GPIOA->MODER &= ~(GPIO_MODER_MODE10_0);
	GPIOA->MODER |= GPIO_MODER_MODE10_1;
	GPIOA->MODER &= ~(GPIO_MODER_MODE11_0);
	GPIOA->MODER |= GPIO_MODER_MODE11_1;
	
	GPIOA->AFR[1] = 0x1111;
	
	TIM1->PSC = 159;    // 16MHz / 16 = 1MHz 
	TIM1->ARR = 10;
	
	TIM1->CCR1 = 5;
	TIM1->CCR2 = 5;
	TIM1->CCR3 = 5;
	TIM1->CCR4 = 5;
	
	TIM1->CCMR1 |= TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1PE;
	TIM1->CCMR1 |= TIM_CCMR1_OC2M_2 | TIM_CCMR1_OC2M_1 | TIM_CCMR1_OC2PE;
	TIM1->CCMR2 |= TIM_CCMR2_OC3M_2 | TIM_CCMR2_OC3M_1 | TIM_CCMR2_OC3PE;
	TIM1->CCMR2 |= TIM_CCMR2_OC4M_2 | TIM_CCMR2_OC4M_1 | TIM_CCMR2_OC4PE;
	
	TIM1->CCER |= TIM_CCER_CC1E; 
	TIM1->CCER |= TIM_CCER_CC2E; 
	TIM1->CCER |= TIM_CCER_CC3E; 
	TIM1->CCER |= TIM_CCER_CC4E;   
	
	TIM1->BDTR |= TIM_BDTR_MOE; // OC or OCN outputs get EN if their respective CCxE bit is set
	TIM1->CR1 |= TIM_CR1_CEN;
	TIM1->EGR |= TIM_EGR_UG;
}

void PWM_CH4(void){
		RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	GPIOA->MODER &= ~(GPIO_MODER_MODE11_0);
	GPIOA->MODER |= GPIO_MODER_MODE11_1;
	
	GPIOA->AFR[1] = 0x1000;
	
	TIM1->PSC = 159;    // 16MHz / 16 = 1MHz 
	TIM1->ARR = 10;
	TIM1->CCR4 = 5;
	TIM1->CCMR2 |= TIM_CCMR2_OC4M_1 | TIM_CCMR2_OC4M_2 | TIM_CCMR2_OC4PE;
	TIM1->CCER |= TIM_CCER_CC4E;              
	TIM1->BDTR |= TIM_BDTR_MOE; // OC or OCN outputs get EN if their respective CCxE bit is set
	TIM1->CR1 |= TIM_CR1_CEN;
	TIM1->EGR |= TIM_EGR_UG;
}
